//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularJsProjectApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ScheduleContext : DbContext
    {
        public ScheduleContext()
            : base("name=ScheduleContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Day> Day { get; set; }
        public virtual DbSet<GROUP> GROUP { get; set; }
        public virtual DbSet<Hour10> Hour10 { get; set; }
        public virtual DbSet<Hour11> Hour11 { get; set; }
        public virtual DbSet<Hour12> Hour12 { get; set; }
        public virtual DbSet<Hour13> Hour13 { get; set; }
        public virtual DbSet<Hour14> Hour14 { get; set; }
        public virtual DbSet<Hour15> Hour15 { get; set; }
        public virtual DbSet<Hour8> Hour8 { get; set; }
        public virtual DbSet<Hour9> Hour9 { get; set; }
    }
}
